<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerT0ttxl3\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerT0ttxl3/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerT0ttxl3.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerT0ttxl3\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerT0ttxl3\appProdProjectContainer([
    'container.build_hash' => 'T0ttxl3',
    'container.build_id' => '3755f24d',
    'container.build_time' => 1761151306,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerT0ttxl3');
