<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKxt0ult\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKxt0ult/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerKxt0ult.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerKxt0ult\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerKxt0ult\appDevDebugProjectContainer([
    'container.build_hash' => 'Kxt0ult',
    'container.build_id' => 'c40df330',
    'container.build_time' => 1761151422,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKxt0ult');
