
services:
  prestashop:
    image: prestashop/prestashop:1.7.8
    container_name: prestashop
    depends_on:
      - db
    ports:
      - "8080:80"
      - "8443:443"
    environment:
      - PS_DEV_MODE=1
      - DB_SERVER=db
      - DB_NAME=prestashop
      - DB_USER=prestashop
      - DB_PASSWD=prestashop
      - PS_LANGUAGE=en
      - PS_COUNTRY=US
      - PS_FOLDER_ADMIN=admin
      - PS_FOLDER_INSTALL=install
    command: /bin/bash -c "a2enmod ssl && apache2-foreground"
    volumes:
      - ./prestashop:/var/www/html
      - ./apache-conf/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./apache-conf/ssl:/etc/ssl/certs
    restart: unless-stopped

  db:
    ports:
      - "3306:3306"
    image: mysql:5.7
    container_name: prestashop-db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=prestashop
    volumes:
      - ./mysql:/var/lib/mysql
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql  # impor
    restart: unless-stopped
