services:
  prestashop:
    image: oskarw7/biznes-elektroniczny
    ports:
      - "19779:443"
    environment:
      - PS_DEV_MODE=1
      - DB_SERVER=admin-mysql_db
      - DB_NAME=BE_197797
      - DB_USER=root
      - DB_PASSWD=student
    command: /bin/bash -c "a2enmod ssl && apache2-foreground"
    networks:
      - admin-mysql_default

networks:
  admin-mysql_default:
    external: true
